/**
 * @file data_fr.js
 * @description Traductions françaises des noms d'items pour Skyrim Checklist.
 *   Chargé après data.js dans index.html.
 *   Format : { [id]: 'Nom en français' }
 *   Si un item n'est pas traduit, il n'apparaît pas dans cet objet
 *   et l'app affiche le nom anglais par défaut.
 */

const DATA_FR_NAMES = {

  // ══════════════════════════════════════════════════════
  // QUESTS — Main Quest (IDs 1–19, 542)
  // ══════════════════════════════════════════════════════
  1: 'Libération',
  2: 'Avant la tempête',
  3: 'Tertre des Chutes Tourmentées',
  4: "L'élévation du dragon",
  5: "L'art de la Voix",
  6: 'La corne de Jurgen Parlevent',
  7: 'Une Lame dans l\'ombre',
  8: 'Immunité diplomatique',
  9: 'Coincé dans la Souricière',
  10: 'Le Mur d\'Alduin',
  11: 'La Gorge du monde',
  12: 'Savoir ancien',
  13: 'Le trépas d\'Alduin',
  14: 'Le déchu',
  15: 'Paarthurnax (optionnel)',
  16: 'Saison éternelle (optionnel)',
  17: 'Le repaire du monstre',
  18: 'Sovngarde',
  19: 'La chasse au dragon',
  542: 'Épilogue',

  // ══════════════════════════════════════════════════════
  // QUESTS — Companions (IDs 20–38)
  // ══════════════════════════════════════════════════════
  20: 'Prenez les armes',
  21: "Une question d'honneur",
  22: 'La Main d\'argent',
  23: "Dette de sang",
  24: 'Pure vengeance',
  25: 'Gloire funèbre',
  26: 'Extermination animale (I)',
  27: 'Extermination animale (II)',
  28: 'Mercenariat',
  29: 'La Défense de Bordeciel',
  30: 'Héritage de famille',
  31: 'Criminel en fuite',
  32: 'Mission de sauvetage',
  33: 'Au cœur de la cible',
  34: 'Le vol des plans',
  35: 'Collection de peau',
  36: 'Les totems d\'Hircine',
  37: 'Pureté',
  38: 'Chercheurs de dragons',

  // ══════════════════════════════════════════════════════
  // QUESTS — College of Winterhold (IDs 39–64)
  // ══════════════════════════════════════════════════════
  39: 'Premières leçons',
  40: 'Sous Saarthal',
  41: 'Les livres perdus',
  42: 'Les meilleures intentions',
  43: "Révélation de l'Invisible",
  44: "État d'urgence",
  45: 'Le Bâton de Magnus',
  46: "L'Œil de Magnus",
  47: "Entraînement de Brelyna",
  48: "L'expérience de J'zargo",
  49: 'La demande d\'Onmund',
  50: 'Perte d\'équilibre',
  51: "L'entreprise d'Arniel",
  52: 'Noms oubliés',
  53: "Rituel d'Altération",
  54: 'Rituel de Conjuration',
  55: 'Rituel de Destruction',
  56: "Rituel d'Illusion",
  57: 'Rituel de Guérison',
  58: "L'alambic de Tolfdir",
  59: 'Réapprovisionnement spirituel',
  60: 'Voyage enchanté',
  61: 'Livres précieux',
  62: 'Les réflexions de Shalidor',
  63: 'Réplique',
  64: 'Mage renégat',

  // ══════════════════════════════════════════════════════
  // QUESTS — Thieves Guild (IDs 65–91)
  // ══════════════════════════════════════════════════════
  65: 'La supercherie de Brynjolf',
  66: 'Les affaires sont les affaires',
  67: 'Sans ambiguïté',
  68: 'Découragement',
  69: "L'imprudence de l'amateur",
  70: 'Le Silence est d\'or',
  71: 'Obscures réponses',
  72: 'La poursuite',
  73: 'La Trinité restaurée',
  74: 'Aveuglement',
  75: 'Vision nocturne',
  76: 'Une nouvelle direction',
  77: 'Vols en pagaille',
  78: "Contrebande de sucre de lune",
  79: "Échange d'armure",
  80: 'Cibles de larcin',
  81: 'Delvin - Saccage',
  82: 'Delvin - Vol à la tire',
  83: 'Delvin - Faux et usage de faux',
  84: 'Vex - Cambriolage',
  85: 'Vex - Pièce à conviction',
  86: 'Vex - Tout doit disparaître',
  87: 'Vex - Rapine',
  88: 'Le Sload Douillet',
  89: 'Le Sload Douillet',
  90: 'Une amnistie méritée',
  91: 'Les ombres de l\'Automne',

  // ══════════════════════════════════════════════════════
  // QUESTS — Dark Brotherhood (IDs 92–122, 543–546)
  // ══════════════════════════════════════════════════════
  92: 'Les aléas du voyage (optionnel)',
  93: 'La fin de l\'innocence',
  94: 'Mauvaises fréquentations',
  95: 'Sanctuaire',
  96: 'Un deuil impossible',
  97: 'Chuchotements dans l\'obscurité',
  98: 'Révélation',
  99: "Jusqu'à ce que la mort nous sépare",
  100: 'Un plan machiavélique',
  101: 'Comment soigner la folie',
  102: 'Fatale recette',
  103: "L'assassinat d'un empire",
  104: 'La mort incarnée',
  105: 'Gloire à Sithis !',
  106: 'On n\'est bien que chez soi',
  107: 'La fortune du faible',
  108: 'Localisez l\'assassin d\'anciens',
  109: 'Les victimes de torture (I–IV)',
  110: 'Contrat : Tuer Narfi',
  111: 'Contrat : Tuer Beitild',
  112: 'Contrat : Tuer Ennodius Papius',
  113: 'Contrat : Tuer Hern',
  114: 'Contrat : Tuer Lurbuk',
  115: 'Contrat : Tuer Deekus',
  116: "Contrat : Tuer Ma'randru-jo",
  117: 'Contrat : Tuer Anoriath',
  118: 'Contrat : Tuer Agnis',
  119: 'Contrat : Tuer Maluril',
  120: 'Contrat : Tuer Helvard',
  121: 'Contrat : Tuer Safia',
  122: 'Longue vie à la Confrérie noire',
  543: 'Anéantissez la Confrérie noire ! (alternative)',
  544: 'Honore ta famille',
  545: 'Bienvenue dans la Confrérie',
  546: 'Le retour de Cicéron',

  // ══════════════════════════════════════════════════════
  // QUESTS — Civil War — Imperial Legion (IDs 123–136)
  // ══════════════════════════════════════════════════════
  123: 'Dans la Légion',
  124: 'La Couronne d\'Os',
  125: 'Un message pour Blancherive',
  126: 'Combattez pour Blancherive',
  127: 'La réunification de Bordeciel',
  128: 'Falsification',
  129: 'La bataille de Fort Dunstad',
  130: 'Un lourd tribut',
  131: 'La bataille de Fort Busard',
  133: 'Délivrance à Fort Kastav',
  135: 'La bataille de Fort Amol',
  136: 'Combattez pour Vendeaume',

  // QUESTS — Civil War — Stormcloaks (IDs 137–151)
  137: 'Avec les Sombrages',
  138: 'La Couronne d\'Os',
  139: 'Un message pour Blancherive',
  140: 'Combattez pour Blancherive',
  141: 'La libération de Bordeciel',
  142: 'Délivrance à Fort Néograd',
  143: 'Un lourd tribut',
  144: 'La bataille de Fort Gardesol',
  145: 'Falsification',
  146: 'La bataille de Fort Busard',
  150: 'La bataille de Fort Hraggstad',
  151: 'Combattez pour Solitude',

  // ══════════════════════════════════════════════════════
  // QUESTS — Daedric (IDs 152–166)
  // ══════════════════════════════════════════════════════
  152: "L'Étoile Noire",
  153: "L'appel de Boéthia",
  154: 'Un Daedra pour ami',
  155: "La quête de l'extraordinaire",
  156: 'Un soir au clair de lune',
  157: 'La tribu maudite',
  158: 'Les fragments du passé',
  159: 'La porte murmurante',
  160: "La lumière de l'aube",
  161: 'La maison des horreurs',
  162: 'Le goût de la mort',
  163: 'Le seul remède',
  164: 'Une nuit mémorable',
  165: 'La folie incarnée',
  166: 'La fin du cauchemar',

  // ══════════════════════════════════════════════════════
  // QUESTS — Bards College (IDs 167–170)
  // ══════════════════════════════════════════════════════
  167: 'À petit feu',
  168: 'La flûte de Pantéa',
  169: 'Le luth de Finn',
  170: 'Le tambour de Rjorn',

  // ══════════════════════════════════════════════════════
  // QUESTS — Divine Quests (IDs 171–176)
  // ══════════════════════════════════════════════════════
  171: 'Les épreuves sacrées de Kyne',
  172: 'Les bienfaits de la Nature',
  173: 'Le cœur de Dibella',
  174: 'Le livre d\'amour',
  175: 'Propagez l\'amour',
  176: 'Les liens du mariage',

  // ══════════════════════════════════════════════════════
  // QUESTS — The Greybeards (ID 177)
  // ══════════════════════════════════════════════════════
  177: 'Révélations du Mur des Mots',

  // ══════════════════════════════════════════════════════
  // QUESTS — The Blades (IDs 178–182)
  // ══════════════════════════════════════════════════════
  178: 'Reformer les Lames',
  179: 'Chasses au dragon',
  180: 'Recherche sur les dragons',
  181: 'Bénédiction du tueur de dragons',
  182: 'La potion d\'Esbern',

  // ══════════════════════════════════════════════════════
  // QUESTS — Side Quests (IDs 183–202, 547–551)
  // ══════════════════════════════════════════════════════
  183: 'La Mine de Cidhna',
  184: 'La conspiration des Parjures',
  185: "L'Expédition perdue",
  186: 'Repose en paix',
  187: 'Résistance à l\'est',
  188: 'Promesses tenues',
  189: 'Profondeurs insondables',
  190: 'Extinction des feux',
  191: "L'homme qui criait au loup",
  192: 'Le réveil de la Reine-Louve',
  193: 'À la demande d\'une dame',
  194: 'Absent au combat',
  195: 'Du sang sur la glace',
  196: 'Rafistolage de Fiole',
  197: 'Résistance à l\'est',
  198: 'La Fiole Blanche',
  199: 'La Griffe d\'Or',
  200: 'Une Légende Interdite',
  201: 'Les Doigts du Forgeron',
  202: 'Un retour aux sources',
  547: 'Le Guerrier d\'Ébonite',
  548: 'Perdue dans les Âges',
  549: 'Créatures capturées',
  550: 'La Grande Chasse aux Trésors de Bordeciel',
  551: 'Masques des Prêtres Dragons',

  // ══════════════════════════════════════════════════════
  // QUESTS — Dungeon Quests (IDs 203–225)
  // ══════════════════════════════════════════════════════
  203: 'Medresi Dran et les Morts-Vivants',
  204: 'Un amour par-delà la mort',
  205: 'Sang-froid, vitesse et précision',
  206: 'Regardez avant de sauter',
  207: 'Melka et Petra',
  208: 'Repentir',
  209: 'Assiégez le Culte du Dragon',
  210: 'Ce qui gît dans les profondeurs',
  211: 'La Dame Pâle',
  212: 'Le parchemin d\'Anska',
  213: 'Culte ancestral',
  214: 'Oubliez Fjola',
  215: 'Chasseur et chassé',
  216: "L'arnaque de Nilheim",
  217: 'Les fous gardiens d\'Otar',
  218: 'La légende de l\'Aigle Rouge',
  219: "Le spectre de Wilhelm",
  220: 'Le secret de l\'arbre dormant',
  221: 'Le sauveteur de Selveni Nethri',
  222: 'Infiltration',
  223: 'Le mal en attente',
  224: 'Langues réduites au silence',
  225: 'Échoué dans une mer de fantômes',

  // ══════════════════════════════════════════════════════
  // QUESTS — Miscellaneous Objectives (IDs 226–326)
  // ══════════════════════════════════════════════════════
  226: 'La Jument Pavoisée',
  227: "L'Auberge du Géant Endormi",
  228: "L'Auberge du Fruit Givré",
  229: 'Le Skeever Clignotant',
  230: 'La Taverne aux Quatre Boucliers',
  231: "L'Auberge du Sang d'Argent",
  232: "L'Auberge du Vieux Hroldan",
  233: "L'Abeille et la Barbe",
  234: "L'Auberge de Vilemyr",
  235: 'La Salle des Flammes',
  236: 'Le Club du Coin de Gnisis',
  237: "L'Auberge de Braidwood",
  238: "L'Auberge du Pic des Vents",
  239: "L'Auberge de la Porte de Nuit",
  240: "L'Auberge des Landes",
  241: 'Le Foyer Gelé',
  242: 'Le Netch Vomisseur',
  243: 'La Pension de Haelga',
  244: 'La Chope Déchirée',
  245: 'Le Chasseur Ivre',
  246: 'Le tribut d\'Elisif',
  247: 'Pas de nouvelles, bonnes nouvelles',
  248: 'Digne d\'un Jarl',
  249: 'Retour à la grâce',
  250: 'Livraison de vin épicé',
  251: 'Livrer le rhum de Stros M\'Kai',
  252: "L'hydromel Souffle du Dragon",
  253: 'Les habitudes nocturnes de Falion',
  254: 'La lettre de Gorm',
  255: 'Livraisons lentes à Bryling',
  256: 'Sel de mer',
  257: 'Nouvelle lune',
  258: 'Apprentis disparus : Borvir',
  259: 'Apprentis disparus : Ilas-tei',
  260: 'Apprentis disparus : Rundi',
  261: 'Apprentis disparus : Yisra',
  262: 'Trouver Isabelle',
  263: "L'épée de Gharol",
  264: "La mine de Sauranach : Aider Atar",
  265: "La mine de Sauranach : Aider Ainethach",
  266: 'Nettoyage de Kolskeggr',
  267: "L'anneau de Calcelmo",
  268: 'La beauté de Dibella',
  269: 'La potion de l\'Intendant',
  270: 'Le dernier fourreau',
  271: 'Triomphe sur Talos',
  272: "Le cœur du problème",
  273: 'Neutraliser Nimhe',
  274: 'Le fantôme du Vieux Hroldan',
  275: 'Lettre à Leonitus',
  276: 'Boucher les trous',
  277: 'Erik le Tueur',
  278: 'Le triangle amoureux : Aider Sven',
  279: 'Le triangle amoureux : Trahir Sven',
  280: 'Le triangle amoureux : Aider Faendal',
  281: 'Le triangle amoureux : Trahir Faendal',
  282: 'Intimidation de Braith',
  283: 'Extraction de l\'Ale Argonien',
  284: 'Une grande épée pour un grand homme',
  285: "L'amulette d'Arkay d'Andurs",
  286: 'Sel pour Arcadia',
  287: 'Extraire un Argonien',
  288: 'Sel pour le Tailleur de Pierre',
  289: 'Coupe équipage',
  290: 'Obscurcine pour les morts',
  291: 'La longue ombre de Malborn',
  292: 'Un jour Thalmor...',
  293: 'Vighar le vampire',
  294: 'Combattre ou fuir',
  295: 'La goutte qui fait déborder',
  296: 'Sourire et supporter',
  297: 'Grimpez les marches',
  298: "S'incliner devant le Maître",
  299: "La plainte de l'amant",
  300: 'Sous la table',
  301: 'Rares et précieux',
  302: 'Propagez l\'amour',
  303: 'Sceller l\'accord',
  304: 'Froid polaire',
  305: 'Souvenirs lointains',
  306: 'Le retour de Brise-glaive',
  307: 'Attiser les flammes',
  308: 'Prise en flagrant délit',
  309: 'Pèlerinage',
  310: 'Chasse et cueillette',
  311: 'Livraison spéciale',
  312: 'Apportez-le !',
  313: 'Conséquences minières',
  314: 'Bijoutier',
  315: 'Coup de sang',
  316: 'Jouer avec les morts',
  317: 'Éclat et Saphir',
  318: "La quête du Jarl, Partie 1 : Un coup de main",
  319: "La quête du Jarl, Partie 2 : Le raid",
  320: "La quête du Jarl, Partie 3 : Offre et demande",
  321: "Effacer la dette de Vald",
  322: 'La vengeance de Gissur',
  323: 'Shavari l\'assassin',
  324: 'Smooth Jazboy',
  325: 'La mine, la mienne',
  326: 'Lettres pour M. Casse-Pierres',

  // ══════════════════════════════════════════════════════
  // QUESTS — Favors (IDs 327–436) — NPC names, peu traduits
  // (Les noms de PNJ ne sont pas traduits)
  // ══════════════════════════════════════════════════════
  // Thane tasks
  428: 'Seigneur d\'Haafingar',
  429: 'Seigneur de Hjaalmarche',
  430: 'Seigneur du Terne',
  431: 'Seigneur de Faillaise',
  432: 'Seigneur de la Crevasse',
  433: 'Seigneur de Blancherive',
  434: "Seigneur d'Estemarche",
  435: 'Seigneur de Falkereth',
  436: 'Seigneur du Clos',

  // ══════════════════════════════════════════════════════
  // QUESTS — Dawnguard (IDs 437–485)
  // ══════════════════════════════════════════════════════
  437: 'Garde de l\'Aube',
  438: 'Prise de conscience',
  439: 'Liens du sang',
  440: 'Le pouvoir du sang',
  441: 'Le Calice de Pierresang',
  442: 'Un nouvel ordre',
  443: 'Prophète',
  444: 'Recherche d\'un Parchemin',
  445: 'À la recherche d\'une révélation',
  446: 'À la poursuite des échos',
  447: 'Au-delà de la mort',
  448: 'Visions inédites',
  449: 'Toucher le ciel',
  450: 'Jugement d\'un pair',
  451: 'Parchemins ancestraux à vendre',
  452: 'Réparation du château',
  453: 'La guérison de Serana',
  454: 'Le retour de Valérica',
  455: 'Technologie ancienne',
  456: 'Recruter de nouvelles forces',
  457: 'Lumière purificatrice',
  458: 'Cache-cache',
  459: 'À la chasse au monstre',
  460: 'La justice d\'un Jarl',
  461: 'Relique perdue',
  462: 'Frappe préventive',
  463: 'Sauvetage',
  464: 'Amulettes de pouvoir nocturne',
  465: 'Pouvoir ancien',
  466: 'Mort à la bête',
  467: 'Tromper le troupeau',
  468: 'Décapiter la Garde de l\'Aube',
  469: 'Le cadeau',
  470: 'La chasse',
  471: 'Nouvelles allégeances',
  472: 'Protéger la lignée',
  473: 'Anneaux de magie du sang',
  474: 'Durnehviir',
  475: 'Face à face',
  476: "L'impatience d'un saint",
  477: 'La grande chasse aux trésors de Bordeciel',
  478: 'Trouvez le crâne d\'Arvak',
  479: 'Invocations sombres',
  480: '(N\'ayez pas) Peur du faucheur',
  481: 'Le marchand de coques d\'âme',
  482: 'La concoction de Valérica',
  483: 'L\'âme tout entière',
  484: 'Les anciens livres falmers',
  485: 'Les paragons des Géants du Givre',

  // ══════════════════════════════════════════════════════
  // QUESTS — Dragonborn (IDs 486–541)
  // ══════════════════════════════════════════════════════
  486: 'Enfant de Dragon',
  487: 'Le temple de Miraak',
  488: 'Le destin des Skaals',
  489: 'La purification des pierres',
  490: 'La voie de la connaissance',
  491: 'Le cultivateur des hommes',
  492: 'Au sommet d\'Apocrypha',
  493: 'Les bâtons d\'Azra',
  494: 'Livre Noir : Filament et filigranes',
  495: 'Livre Noir : Le crépuscule caché',
  496: 'Livre Noir : Le régent au teint jaune',
  497: 'Livre Noir : L\'heure du changement',
  498: 'Livre Noir : Les légendes inconnues',
  499: 'Nécropsie de Roncecœur',
  500: 'Le chef de la salle des banquets',
  501: 'Le Balafré',
  502: 'Cobaye',
  503: 'Cœurs de pierre',
  504: 'La descente finale',
  505: 'Retour aux cendres',
  506: 'Remède pour une tour',
  507: 'Vent et sable',
  508: 'Savoir perdu',
  509: "L'héritage perdu",
  510: 'La marche macabre',
  511: 'Une nouvelle source de stahlrim',
  512: 'De vieux amis',
  513: 'Question d\'intendance',
  514: 'Une nouvelle dette',
  515: 'Reprenez Thirsk',
  516: 'Un plat qui se mange froid',
  517: 'Recherche Telvanni',
  518: 'Sorti de terre',
  519: 'Vent et sable',
  520: 'Les épreuves de Kagrumez',
  521: 'La Grande Chasse aux coffres de Solstheim',
  522: 'Invoquer Karstaag',
  523: 'Masques des Prêtres Acolytes',
  524: 'Anneaux des loups-garous',
  525: 'Fabrication d\'araignées',
  526: 'Tous les bienvenus',
  527: 'Embargo Emberbrand',
  528: 'De la gelée pour Milore',
  529: "L'addiction des gardes rédorans",
  530: 'Prenez votre pioche',
  531: 'Vol et connexion Karstaag',
  532: 'Éradicateur de tombes',
  533: 'Razzias de tomes',
  534: 'La plainte d\'une mère',
  535: 'Retour à Falkereth',
  536: 'Les ingrédients d\'Élynea',
  537: 'Yeux et oreilles',
  538: 'Une soif à Thirsk',
  539: 'Baies hors de portée',
  540: 'Minerai inspiré',
  541: 'Bâtons primitifs',

  // ══════════════════════════════════════════════════════
  // QUESTS — Fishing (IDs 552–573)
  // ══════════════════════════════════════════════════════
  552: "Entre pêcheurs",
  553: "À la rigueur",
  554: 'Perspicace',
  555: 'Cœur d\'or',
  556: 'Les deux font la paire',
  557: 'Extermination de crustacés',
  558: 'Terreur cornue',
  559: 'Cours particuliers',
  560: 'Le spiritueux',
  561: 'Le concours',
  562: 'Un festin mémorable',
  563: 'Sous les flots de bronze',
  564: 'Brise-vague',
  565: 'Garder la ligne',
  566: 'Prise du jour',
  567: 'Poisson gelé',
  568: 'Pêche sous la pluie',
  569: 'Les plus sombres profondeurs',
  570: 'Légende de la pêche',
  571: 'Faire des réserves',
  572: 'Étude poussée',
  573: 'Récupération de déchets',

  // ══════════════════════════════════════════════════════
  // QUESTS — Creation Club (IDs 574–657) — traductions partielles
  // ══════════════════════════════════════════════════════
  574: 'Marchand disparu',
  575: 'Par-delà la tombe',
  576: 'Écailles penchées',
  577: 'Des os pour un corbeau',
  578: 'Fan favori',
  579: 'Plus puissant que l\'épée',
  580: 'Cœur de Cramoisi',
  581: 'Chasseur autrefois',
  582: 'Frères en fer',
  583: 'Double tranchant',
  584: 'Forgeron-éclair',
  585: "L'avantage du joueur",
  586: 'Quand le chat n\'est pas là',
  587: 'Glace ancienne',
  588: 'Par-dessus le bord',
  589: 'Don de Kynareth',
  590: 'Préparation de Saturalia',
  591: 'Bataille des champions',
  592: 'Dans l\'ombre',
  593: 'Le paladin perdu',
  594: 'Une âme divisée',
  595: 'Soif de sang',
  596: 'Une question d\'orgueil',
  597: 'Les armes du Chaos',
  598: 'Le bâton de Hasedoki',
  599: 'Mettez-y une fourchette',
  600: 'Si j\'avais un marteau',
  601: 'Légendes perdues',
  602: 'À travers un miroir sombre',
  603: 'Pris dans une toile',
  604: 'La lisière de la ruine',
  605: 'Murmures vils',
  606: 'Du sang dans l\'eau',
  607: 'Interception',
  608: 'Les fantômes du Tribunal',
  609: 'Cœur de cendres',
  610: 'Acheteur méfiant',
  611: 'Curation négligente',
  612: 'Sa parole contre la leur',
  613: 'Vraie Flamme',
  614: 'Équilibre des forces',
  615: 'Rétablir l\'ordre',
  616: 'La quête de Staada',
  617: 'Forge ambre et folie',
  618: 'Forge or et ténèbres',
  619: 'Mon animal Elytra (Démence)',
  620: 'Mon animal Elytra (Manie)',
  621: 'Brise-nerfs',
  622: 'La Cause',
  623: 'Les Conséquences',
  624: 'Un vœu mourant',
  625: 'Le Puits',
  626: 'Fils chanceux',
  627: 'Reliques du Croisé',
  628: 'La voie du pèlerin',
  629: 'Le Capuchon Gris de Nocturnal',
  630: 'Saisons oubliées',
  631: 'La Couronne dwemer',
  632: 'Le Cheval dwemer',
  633: 'Hendraheim',
  634: 'Myrwatch',
  635: 'Le Sanctuaire de l\'Ombre',
  636: 'Invités pour le dîner',
  637: 'Les sans-repos',
  638: 'Rêves des morts',
  639: 'Le Sanctuaire et la Manufacture',
  640: 'Mon animal Bernard',
  641: 'Mon animal Nix-Hound',
  642: 'Animaux de Bordeciel',
  643: 'Laissez dormir les loups',
  644: 'Chuchoteur de chevaux',
  645: 'Créature de légende',
  646: 'Les bleus au visage',
  647: 'Les morts sans repos',
  648: 'Une vie à la ferme',
  649: 'Voleur d\'âmes',
  650: 'Rapide comme une flèche',
  651: 'Plus qu\'on ne peut mâcher',
  652: 'Bijoux nordiques',
  653: 'Crypte du cœur',
  654: 'Veillée impie',
  655: 'Chasseur de nuit',
  656: 'La bibliothèque perdue',
  657: 'Les morts qui se lèvent',

  // ══════════════════════════════════════════════════════
  // DRAGON SHOUTS (IDs 658–738)
  // Les mots draconiques sont des noms propres — pas de traduction.
  // Seule la signification (word_en) est traduite via DATA_FR_WORDS.
  // ══════════════════════════════════════════════════════

  // ══════════════════════════════════════════════════════
  // SPELLS — Alteration (IDs 739–755)
  // ══════════════════════════════════════════════════════
  739: 'Illumination',
  740: 'Corps de chêne',
  741: 'Rayonnement',
  742: 'Corps de pierre',
  743: 'Coquille de cendres',
  744: 'Détection des vivants',
  745: 'Corps de fer',
  746: 'Télékinésie',
  747: 'Respiration aquatique',
  748: 'Rune de cendres',
  749: 'Détection des morts',
  750: "Corps d'ébonite",
  751: 'Paralysie',
  752: 'Cuirasse draconique',
  753: 'Paralysie générale',
  754: 'Équilibre',
  755: 'Transmutation',

  // ══════════════════════════════════════════════════════
  // SPELLS — Conjuration (IDs 756–786)
  // ══════════════════════════════════════════════════════
  756: 'Dague liée',
  757: 'Épée liée',
  758: 'Conjuration de familier',
  759: "Allié d'outre-tombe",
  760: "Hache d'armes liée",
  761: 'Invoquer un homme-os',
  762: "Conjuration d'Atronach de feu",
  763: 'Réanimation',
  764: "Capture d'âme",
  765: 'Invoquer Arvak',
  766: 'Bannissement de Daedra',
  767: 'Arc lié',
  768: 'Invoquer un enfant des cendres',
  769: "Conjuration d'Atronach de glace",
  770: 'Invoquer un homme-brume',
  771: 'Invoquer un chercheur',
  772: 'Revenant',
  773: 'Manipulation de Daedra',
  774: 'Conjuration de Gardien des cendres',
  775: 'Conjuration de Seigneur Drémora',
  776: "Conjuration d'Atronach de foudre",
  777: 'Invoquer un homme-courroux',
  778: 'Surzombie',
  779: 'Expulsion de Daedra',
  780: 'Golem zombie',
  781: 'Golem de feu',
  782: 'Golem de glace',
  783: 'Golem de foudre',
  784: 'Familier de feu',
  785: "Invocation de l'ombre d'Arniel",
  786: 'Invoquer un drémora non lié',

  // ══════════════════════════════════════════════════════
  // SPELLS — Destruction (IDs 787–815)
  // ══════════════════════════════════════════════════════
  787: 'Flammes',
  788: 'Froid mordant',
  789: 'Étincelles',
  790: 'Rune de feu',
  791: 'Éclair enflammé',
  792: 'Gel',
  793: 'Rune de glace',
  794: 'Stalactite',
  795: 'Ignition',
  796: 'Éclair foudroyant',
  797: "Rune de foudre",
  798: 'Éclairs multiples',
  799: 'Boule de feu',
  800: 'Aura enflammée',
  801: 'Aura glaciale',
  802: 'Tempête de glace',
  803: 'Aura foudroyante',
  804: 'Manteau de tourbillon',
  805: 'Lance gelée',
  806: 'Incinération',
  807: 'Trait de foudre',
  808: 'Mur de flammes',
  809: 'Mur de glace',
  810: 'Mur de foudre',
  811: 'Blizzard',
  812: 'Tempête de feu',
  813: 'Tempête de foudre',
  814: "Convection d'Arniel",
  815: 'Drain vampirique',

  // ══════════════════════════════════════════════════════
  // SPELLS — Illusion (IDs 816–832)
  // ══════════════════════════════════════════════════════
  816: 'Courage',
  817: 'Clairvoyance',
  818: 'Furie',
  819: 'Calme',
  820: 'Peur',
  821: 'Silence',
  822: 'Frénésie',
  823: 'Rune de frénésie',
  824: 'Inspiration',
  825: 'Invisibilité',
  826: 'Pacification',
  827: 'Déroute',
  828: 'Appel aux armes',
  829: 'Harmonie',
  830: 'Hystérie',
  831: 'Pagaille',
  832: 'Vision du Dixième Œil',

  // ══════════════════════════════════════════════════════
  // SPELLS — Restoration (IDs 833–855)
  // ══════════════════════════════════════════════════════
  833: 'Soin',
  834: 'Moindre barrière',
  835: 'Soin rapide',
  836: 'Toucher apaisant',
  837: 'Guérison nécromantique',
  838: 'Moyenne barrière',
  839: 'Feu solaire',
  840: 'Moindre péril des morts',
  841: 'Cicatrisation',
  842: 'Grande barrière',
  843: 'Soulagement',
  844: 'Soigner les morts-vivants',
  845: 'Rune de poison',
  846: 'Moindre fléau des morts',
  847: 'Aura de Stendarr',
  848: 'Péril des morts',
  849: 'Fléau des vampires',
  850: 'Cercle de protection',
  851: 'Soin magistral',
  852: 'Fléau des morts',
  853: 'Grand péril des morts',
  854: 'Calamité des morts-vivants',
  855: 'Cercle gardien',

  // ══════════════════════════════════════════════════════
  // SPELLS — Special / CC Pets (IDs 856–865)
  // ══════════════════════════════════════════════════════
  856: 'Téléporter animal : Arachnia',
  857: 'Téléporter animal : Loup osseux',
  858: 'Téléporter animal : Nymphe Elytra Démente',
  859: 'Téléporter animal : Bernard dwemer',
  860: 'Téléporter animal : Hilda',
  861: 'Téléporter animal : Nymphe Elytra Maniaque',
  862: 'Téléporter animal : Nix-Hound',
  863: 'Téléporter animal : Skritch',
  864: 'Téléporter animal : Choux à la crème',
  865: 'Téléporter animal : Chardon',

  // ══════════════════════════════════════════════════════
  // SPELLS — CC Additional (IDs 866–908)
  // ══════════════════════════════════════════════════════
  866: 'Transmutation maîtresse',
  867: 'Rune de paralysie',
  868: 'Flèches télékinésiques',
  869: 'Invoquer un squeletton mineur',
  870: 'Invoquer un fantôme immortel',
  871: 'Invoquer un zombie',
  872: 'Invoquer un zombie putride',
  873: 'Invoquer un esprit hanté',
  874: 'Invoquer un squelette archer',
  875: 'Division d\'âme',
  876: 'Invoquer un cheval daédrique',
  877: 'Bannir les morts-vivants',
  878: 'Carquois lié',
  879: 'Invoquer une archère Séductrice des Ténèbres',
  880: 'Invoquer une guerrière Séductrice des Ténèbres',
  881: 'Invoquer un archer Saint Doré',
  882: 'Invoquer un guerrier Saint Doré',
  883: 'Invoquer un zombie putride',
  884: 'Invoquer un squelette champion',
  885: 'Invoquer un gardien de tombeau',
  886: 'Rituel du nécromancien',
  887: 'Invoquer un spectre maudit',
  888: 'Invoquer un zombie malin',
  889: 'Invoquer un squelette mage',
  890: 'Fierté de Hirstaang',
  891: 'Invoquer un liche ayleïd',
  892: 'Invoquer un ancien prêtre de la mort',
  893: 'Invoquer un colosse osseux',
  894: 'Invoquer Staada',
  895: 'Étranglement',
  896: 'Flamboiement élémentaire',
  897: 'Carreau élémentaire',
  898: 'Strangulation',
  899: 'Explosion élémentaire',
  900: 'Nœud du pendu',
  901: 'Déflagration élémentaire',
  902: 'La Colère de Mara',
  903: 'Toucher mortel',
  904: 'Flammes déchaînées',
  905: 'Gel déchaîné',
  906: 'Tempêtes déchaînées',
  907: "L'Évasion aquatique d'Orum",
  908: "L'Accueil de Fenrik",

  // ══════════════════════════════════════════════════════
  // ENCHANTING EFFECTS — Weapons (IDs 909–922)
  // ══════════════════════════════════════════════════════
  909: 'Siphon de santé',
  910: 'Siphon de magie',
  911: 'Siphon de vigueur',
  912: 'Bannissement',
  913: 'Dégâts de chaos',
  914: 'Peur',
  915: 'Dégâts de feu',
  916: 'Dégâts de glace',
  917: 'Dégâts magiques',
  918: 'Paralysie',
  919: 'Dégâts de foudre',
  920: 'Capture d\'âme',
  921: 'Dégâts de vigueur',
  922: 'Repousser les morts-vivants',

  // ══════════════════════════════════════════════════════
  // ENCHANTING EFFECTS — Armor (IDs 923–961)
  // ══════════════════════════════════════════════════════
  923: 'Renfort d\'alchimie',
  924: 'Renfort d\'altération',
  925: 'Renfort d\'archerie',
  926: 'Renfort de parade',
  927: 'Renfort de portage',
  928: 'Renfort de conjuration',
  929: 'Renfort de destruction',
  930: 'Régénération de santé',
  931: 'Renfort de santé',
  932: 'Renfort d\'armure lourde',
  933: 'Renfort d\'illusion',
  934: 'Renfort d\'armure légère',
  935: 'Renfort de crochetage',
  936: 'Renfort de magie',
  937: 'Régénération de magie',
  938: 'Renfort d\'arme à une main',
  939: 'Renfort de vol à la tire',
  940: 'Renfort de guérison',
  941: 'Renfort de forgeage',
  942: 'Renfort de furtivité',
  943: 'Renfort de marchandage',
  944: 'Renfort de vigueur',
  945: 'Régénération de vigueur',
  946: 'Renfort d\'arme à deux mains',
  947: 'Silence',
  948: 'Résistance à la maladie',
  949: 'Résistance au feu',
  950: 'Résistance au froid',
  951: 'Résistance à la magie',
  952: 'Résistance au poison',
  953: 'Résistance à la foudre',
  954: 'Respiration aquatique',
  955: 'Dégâts à mains nues',
  956: 'Capture d\'âme ardente',
  957: 'Prouesse du chasseur',
  958: 'Enchantement de la Lune Silencieuse',
  959: 'Expertise de forge',
  960: 'Lune sombre',
  961: 'Renfort de nécromancie',

  // ══════════════════════════════════════════════════════
  // ALCHEMY INGREDIENTS (IDs 962–1144)
  // ══════════════════════════════════════════════════════
  962: 'Abécéen à longue nageoire',
  963: 'Fruit d\'Alocasia',
  964: 'Feuilles d\'aloès',
  965: 'Ambroisie',
  966: 'Aile de mite ancestrale',
  967: 'Poisson-ange',
  968: 'Larves de pêcheur',
  969: 'Cosse cendrée',
  970: 'Gelée de sautecendres',
  971: 'Cosse de cendres',
  972: 'Cœur d\'Aster',
  973: 'Griffes d\'ours',
  974: 'Abeille',
  975: 'Ruche vide',
  976: 'Pétales d\'Amertiverde',
  977: 'Œil du veilleur aveugle',
  978: 'Thorax de Flammouche',
  979: 'Chapeau de cosse vésiculeuse',
  980: 'Couronne sanglante',
  981: 'Cloquerille',
  982: 'Herbe de sang',
  983: 'Aile de papillon bleu',
  984: 'Aile de fléchette bleue',
  985: 'Lys des cimes bleu',
  986: 'Défense de sanglier',
  987: 'Mycène des marais',
  988: 'Farine d\'os',
  989: 'Cœur de ronces',
  990: 'Flétrissant',
  991: 'Bois de spriggan brûlé',
  992: 'Aile de papillon',
  993: 'Racine de canis',
  994: 'Peau de ragnard carbonisé',
  995: 'Œuf de chaurus',
  996: 'Antennes de chasseur Chaurus',
  997: 'Œuf de poule',
  998: 'Choucard',
  999: 'Chokeweed',
  1000: 'Fleur de Coda',
  1001: 'Comberry',
  1002: 'Putrescence congelée',
  1003: 'Racine de Liègeboule',
  1004: 'Plantes grimpantes',
  1005: 'Nirnroot cramoisie',
  1006: 'Cyriodil à palettes',
  1007: 'Cœur de Daedra',
  1008: 'Soie de Daedra',
  1009: 'Venin de Daedra',
  1010: 'Dents de Daedroth',
  1011: 'Grelot-de-la-mort',
  1012: 'Langue de dragon',
  1013: 'Cire de Dreugh',
  1014: 'Huile dwemer',
  1015: 'Ectoplasme',
  1016: 'Ichor d\'Elytra',
  1017: 'Oreille d\'Elfe',
  1018: 'Mousse-parasol',
  1019: 'Œil de smilodon',
  1020: 'Oreille de Falmer',
  1021: 'Plumes de sterne de Felsaad',
  1022: 'Pétale de feu',
  1023: 'Sels de feu',
  1024: 'Tige de flamme',
  1025: 'Amanite tue-mouches',
  1026: 'Hivernelle',
  1027: 'Sels de givre',
  1028: 'Tige de champignon',
  1029: 'Ail',
  1030: 'Lichen géant',
  1031: 'Orteil de géant',
  1032: 'Poisson de verre',
  1033: 'Brillefleur',
  1034: 'Poussière luisante',
  1035: 'Champignon luisant',
  1036: 'Écorce de Gnarl',
  1037: 'Kanet doré',
  1038: 'Cyprin doré',
  1039: 'Cosse',
  1040: 'Aile de papillon vert',
  1041: 'Feuille de Hackle-Lo',
  1042: 'Serre d\'harfreuse',
  1043: 'Plumes d\'harfreuse',
  1044: 'Mousse barbue',
  1045: 'Harrada',
  1046: 'Bec de faucon',
  1047: 'Plumes de faucon',
  1048: 'Œuf de faucon',
  1049: 'Cœur de l\'Ordre',
  1050: 'Carpe du Hist',
  1051: 'Rayons de miel',
  1052: 'Chair humaine',
  1053: 'Cœur humain',
  1054: 'Langue de faim',
  1055: 'Grande spore azurée',
  1056: 'Hypha Facia',
  1057: 'Dents de spectre de glace',
  1058: 'Fiel de lutin',
  1059: 'Pied-de-lutin',
  1060: 'Fruit de Boisfer',
  1061: 'Raisin jazbay',
  1062: 'Genièvres',
  1063: 'Jeune Bernard',
  1064: 'Peau de Kagouti',
  1065: 'Fibre de Kresh',
  1066: 'Grande ramure',
  1067: 'Lavande',
  1068: 'Lichor',
  1069: 'Aile de noctuelle',
  1070: 'Mycène lumineux',
  1071: 'Anthias à queue de lyre',
  1072: 'Marshmerrow',
  1073: 'Corne de Minotaure',
  1074: 'Sucre de lune',
  1075: 'Mora Tapinella',
  1076: 'Chair de Mort',
  1077: 'Chitine de vasard',
  1078: 'Truffe de Namira',
  1079: 'Gelée de netch',
  1080: 'Obscurcine',
  1081: 'Nirnroot',
  1082: 'Bernache nordique',
  1083: 'Dents d\'ogre',
  1084: 'Aile de fléchette orange',
  1085: 'Perle',
  1086: 'Poisson-perle',
  1087: 'Œuf de grive',
  1088: 'Floraison empoisonnée',
  1089: 'Défense de mammouth en poudre',
  1090: 'Aile de papillon violet',
  1091: 'Lys des cimes violet',
  1092: 'Poisson-soleil nain',
  1093: 'Poche à gaz d\'algue rouge',
  1094: 'Lys des cimes rouge',
  1095: 'Fleur rouge',
  1096: 'Poisson de rivière',
  1097: 'Œuf de fauvette',
  1098: 'Roobrush',
  1099: 'Écaille de pourriture',
  1100: 'Dent de smilodon',
  1101: 'Œufs de saumon',
  1102: 'Tas de sel',
  1103: 'Saltrice',
  1104: 'Nageoire de Scalon',
  1105: 'Pholiote à écailles',
  1106: 'Cosse cendrée',
  1107: 'Mâchoire hurlante',
  1108: 'Gelée de Scrib',
  1109: 'Jerky de Scrib',
  1110: 'Perche argentée',
  1111: 'Queue de ragnard',
  1112: 'Œuf de poisson carnassier',
  1113: 'Écailles de poisson carnassier',
  1114: 'Savon de Sload',
  1115: 'Petite ramure',
  1116: 'Petite perle',
  1117: 'Givreboises',
  1118: 'Poisson-pelle',
  1119: 'Cendres d\'engeance',
  1120: 'Œuf d\'araignée',
  1121: 'Baguette de Spiddal',
  1122: 'Sève de spriggan',
  1123: 'Entolome bleu acier',
  1124: 'Pétales de tige de pierre',
  1125: 'Mycène des marais',
  1126: 'Racine noueuse',
  1127: 'Tige de chardon',
  1128: 'Crochet épineux',
  1129: 'Thorax de luciole',
  1130: 'Racine de trama',
  1131: 'Graisse de troll',
  1132: 'Coton sauvage',
  1133: 'Poussière de vampire',
  1134: 'Essence du Vide',
  1135: 'Sels du Néant',
  1136: "Œil du veilleur",
  1137: 'Blé',
  1138: 'Chapeau-blanc',
  1139: 'Cosse sauvage',
  1140: 'Chapeaux de Tige-Fantôme',
  1141: 'Voiles éthérés',
  1142: 'Lune fanée',
  1143: 'Chapeau de Ver',
  1144: 'Lys des cimes jaune',

};

/**
 * Traductions françaises des significations des mots de cri (word_en).
 * Format : { [itemId]: 'traduction FR' }
 * Utilisé dans le rendu Dragon Shouts à la place de item.word_en en mode FR.
 */
const DATA_FR_WORDS = {
  // Animal Allegiance
  658: 'Animale', 659: 'Allégeance', 660: 'Meute',
  // Aura Whisper
  661: 'Vie', 662: 'Chercher', 663: 'Chasse',
  // Battle Fury
  664: 'Loyal', 665: 'Valeur', 666: 'Inspirer',
  // Become Ethereal
  667: 'Effacement', 668: 'Esprit', 669: 'Lien',
  // Bend Will
  670: 'Pierre/Terre', 671: 'Esprit', 672: 'Dragon',
  // Call Dragon
  673: 'Neige', 674: 'Chasseur', 675: 'Aile',
  // Call of Valor
  676: 'Héros', 677: 'Champion', 678: 'Légende',
  // Clear Skies
  679: 'Ciel', 680: 'Printemps', 681: 'Été',
  // Cyclone
  682: 'Vent', 683: 'Libérer', 684: 'Frappe',
  // Disarm
  685: 'Arme', 686: 'Main', 687: 'Défaite',
  // Dismaying Shout
  688: 'Peur', 689: 'Fuite', 690: 'Terreur',
  // Dragon Aspect
  691: 'Force', 692: 'Armure', 693: 'Dragon',
  // Dragonrend
  694: 'Mortel', 695: 'Fini', 696: 'Temporaire',
  // Drain Vitality
  697: 'Endurance', 698: 'Magicka', 699: 'Santé',
  // Elemental Fury
  700: 'Air', 701: 'Bataille', 702: 'Grâce',
  // Fire Breath
  703: 'Feu', 704: 'Brasier', 705: 'Soleil',
  // Frost Breath
  706: 'Givre', 707: 'Froid', 708: 'Gel',
  // Ice Form
  709: 'Glace', 710: 'Chair', 711: 'Statue',
  // Kyne's Peace
  712: 'Kyné', 713: 'Paix', 714: 'Confiance',
  // Marked for Death
  715: 'Tuer', 716: 'Drain', 717: 'Souffrir',
  // Slow Time
  718: 'Temps', 719: 'Sable', 720: 'Éternité',
  // Soul Tear
  721: 'Essence', 722: 'Déchirer', 723: 'Zombie',
  // Storm Call
  724: 'Tempête', 725: 'Colère', 726: 'Éclair',
  // Summon Durnehviir
  727: 'Malédiction', 728: 'Jamais', 729: 'Mourant',
  // Throw Voice
  730: 'Voix', 731: 'Tromper', 732: 'Loin',
  // Unrelenting Force
  733: 'Force', 734: 'Équilibre', 735: 'Pousser',
  // Whirlwind Sprint
  736: 'Tourbillon', 737: 'Fureur', 738: 'Tempête',
};
